apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: prometheus-blackbox-exporter.rules-rules
  namespace: monitoring
spec:
  groups:
    - name: blackbox-exporter.rules
      rules:
        - alert: BlackboxProbeFailed
          annotations:
            description: |-
              Probe failed
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox probe failed (instance {{ $labels.instance }})
          expr: probe_success == 0
          for: 3m
          labels:
            severity: critical
        - alert: BlackboxSlowProbe
          annotations:
            description: |-
              Blackbox probe took more than 5s to complete
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox slow probe (instance {{ $labels.instance }})
          expr: avg_over_time(probe_duration_seconds[1m]) > 5
          for: 3m
          labels:
            severity: warning
        - alert: BlackboxProbeHttpFailure
          annotations:
            description: |-
              HTTP status code is not 200-399
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
          expr: probe_success != 0 AND (probe_http_status_code <= 199 OR probe_http_status_code >= 400)
          for: 3m
          labels:
            severity: critical
        - alert: BlackboxSslCertificateWillExpireSoon
          annotations:
            description: |-
              SSL certificate expires in 30 days
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
          for: 0m
          labels:
            severity: warning
        - alert: BlackboxSslCertificateWillExpireSoon
          annotations:
            description: |-
              SSL certificate expires in 10 days
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 10
          for: 0m
          labels:
            severity: major
        - alert: BlackboxSslCertificateExpired
          annotations:
            description: |-
              SSL certificate has expired already
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox SSL certificate expired (instance {{ $labels.instance }})
          expr: probe_ssl_earliest_cert_expiry - time() <= 0
          for: 0m
          labels:
            severity: critical
        - alert: BlackboxProbeSlowHttp
          annotations:
            description: |-
              HTTP request took more than 5s
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          expr: avg_over_time(probe_http_duration_seconds[1m]) > 5
          for: 3m
          labels:
            severity: warning
        - alert: BlackboxProbeSlowPing
          annotations:
            description: |-
              Blackbox ping took more than 1s
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
            summary: Blackbox probe slow ping (instance {{ $labels.instance }})
          expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
          for: 3m
          labels:
            severity: warning
